
language: ruby
services:
  - postgresql
before_install:
  #- "gem install bundler"
  - "gem install rack"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
- xvfb-run --server-args="-screen 0 1024x768x24" bundle exec rspec
rvm:
  - 2.2.2
 
